Repository 4und-Cloud/TablePick-BackEnd, pull requests merged in 2025-05, with the labels that each got.

#6 Tp-15 login
  build.gradle
  src/main/java/com/goorm/tablepick/domain/member/dto/GoogleInfo.java
  src/main/java/com/goorm/tablepick/domain/member/dto/KakaoInfo.java
  src/main/java/com/goorm/tablepick/domain/member/dto/OAuthInfo.java
  src/main/java/com/goorm/tablepick/domain/member/entity/Member.java
  src/main/java/com/goorm/tablepick/domain/member/entity/RefreshToken.java
  src/main/java/com/goorm/tablepick/domain/member/enums/AccountRole.java
  src/main/java/com/goorm/tablepick/domain/member/enums/Gender.java
  src/main/java/com/goorm/tablepick/domain/member/repository/MemberRepository.java
  src/main/java/com/goorm/tablepick/domain/member/repository/RefreshTokenRepository.java
  src/main/java/com/goorm/tablepick/domain/member/service/CustomOAuth2UserService.java
  src/main/java/com/goorm/tablepick/global/config/SecurityConfig.java
  src/main/java/com/goorm/tablepick/global/config/WebConfig.java
  src/main/java/com/goorm/tablepick/global/jwt/JwtProvider.java
  src/main/java/com/goorm/tablepick/global/jwt/JwtTokenFilter.java
  src/main/java/com/goorm/tablepick/global/jwt/JwtTokenService.java
  src/main/java/com/goorm/tablepick/global/jwt/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/goorm/tablepick/global/security/CustomUserDetails.java
  src/main/java/com/goorm/tablepick/global/security/CustomUserDetailsService.java
  src/main/resources/application.yml
Labels: feat

#8 TP-15 코드 수정
  src/main/java/com/goorm/tablepick/global/jwt/JwtProvider.java
  src/main/java/com/goorm/tablepick/global/jwt/OAuth2AuthenticationSuccessHandler.java
Labels: refactor

#11 TP-41 사용자 정보 조회 API
  src/main/java/com/goorm/tablepick/domain/member/controller/MemberController.java
  src/main/java/com/goorm/tablepick/domain/member/dto/MemberResponseDto.java
  src/main/java/com/goorm/tablepick/domain/member/exception/MemberErrorCode.java
  src/main/java/com/goorm/tablepick/domain/member/exception/MemberException.java
  src/main/java/com/goorm/tablepick/domain/member/service/MemberService.java
  src/main/java/com/goorm/tablepick/domain/member/service/MemberServiceImpl.java
Labels: feat

#15 TP-43 사용자 정보 수정 API
  src/main/java/com/goorm/tablepick/domain/member/controller/MemberController.java
  src/main/java/com/goorm/tablepick/domain/member/dto/MemberUpdateRequestDto.java
  src/main/java/com/goorm/tablepick/domain/member/entity/Member.java
  src/main/java/com/goorm/tablepick/domain/member/service/MemberService.java
  src/main/java/com/goorm/tablepick/domain/member/service/MemberServiceImpl.java
Labels: feat

#16 TP-40 내 예약 조회 API
  src/main/java/com/goorm/tablepick/domain/member/controller/MemberController.java
  src/main/java/com/goorm/tablepick/domain/member/service/MemberService.java
  src/main/java/com/goorm/tablepick/domain/member/service/MemberServiceImpl.java
  src/main/java/com/goorm/tablepick/domain/reservation/dto/response/ReservationResponseDto.java
  src/main/java/com/goorm/tablepick/domain/reservation/repository/ReservationRepository.java
Labels: feat

#17 TP-39 내 게시글 목록 조회 API
  src/main/java/com/goorm/tablepick/domain/board/dto/MyBoardListResponseDto.java
  src/main/java/com/goorm/tablepick/domain/board/entity/BoardTag.java
  src/main/java/com/goorm/tablepick/domain/board/repository/BoardRepository.java
  src/main/java/com/goorm/tablepick/domain/member/controller/MemberController.java
  src/main/java/com/goorm/tablepick/domain/member/service/MemberService.java
  src/main/java/com/goorm/tablepick/domain/member/service/MemberServiceImpl.java
Labels: feat

#22 TP-46 swagger 설정 추가
  src/main/java/com/goorm/tablepick/global/config/SecurityConfig.java
  src/main/java/com/goorm/tablepick/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: feat

#24 Tp-58 member
  src/main/java/com/goorm/tablepick/domain/board/repository/BoardRepository.java
  src/main/java/com/goorm/tablepick/domain/member/controller/MemberController.java
  src/main/java/com/goorm/tablepick/domain/member/dto/GoogleInfo.java
  src/main/java/com/goorm/tablepick/domain/member/dto/KakaoInfo.java
  src/main/java/com/goorm/tablepick/domain/member/dto/OAuthInfo.java
  src/main/java/com/goorm/tablepick/domain/member/entity/RefreshToken.java
  src/main/java/com/goorm/tablepick/domain/member/repository/RefreshTokenRepository.java
  src/main/java/com/goorm/tablepick/domain/member/service/CustomOAuth2UserService.java
  src/main/java/com/goorm/tablepick/domain/member/service/MemberServiceImpl.java
  src/main/java/com/goorm/tablepick/global/config/SecurityConfig.java
  src/main/java/com/goorm/tablepick/global/jwt/JwtProvider.java
  src/main/java/com/goorm/tablepick/global/jwt/JwtTokenFilter.java
  src/main/java/com/goorm/tablepick/global/jwt/JwtTokenService.java
  src/main/java/com/goorm/tablepick/global/jwt/OAuth2AuthenticationSuccessHandler.java
Labels: refactor

#19 Tp-32 board
  src/main/java/com/goorm/tablepick/domain/board/controller/BoardController.java
  src/main/java/com/goorm/tablepick/domain/board/controller/BoardTagController.java
  src/main/java/com/goorm/tablepick/domain/board/dto/request/BoardFilterRequest.java
  src/main/java/com/goorm/tablepick/domain/board/dto/request/BoardRequestDto.java
  src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardDetailResponseDto.java
  src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardListResponseDto.java
  src/main/java/com/goorm/tablepick/domain/board/entity/Board.java
  src/main/java/com/goorm/tablepick/domain/board/entity/BoardImage.java
  src/main/java/com/goorm/tablepick/domain/board/entity/BoardTag.java
  src/main/java/com/goorm/tablepick/domain/board/repository/BoardTagRepository.java
  src/main/java/com/goorm/tablepick/domain/board/service/BoardService.java
  src/main/java/com/goorm/tablepick/domain/board/service/BoardTagService.java
  src/main/java/com/goorm/tablepick/domain/tag/entity/Tag.java
  src/main/java/com/goorm/tablepick/domain/tag/repository/TagRepository.java
Labels: feat

#30 [TP-61] 게시물 코드 리팩토링
  src/main/java/com/goorm/tablepick/domain/board/controller/BoardController.java
  src/main/java/com/goorm/tablepick/domain/board/entity/BoardImage.java
Labels: enhancement

#29 Tp-44 search
  src/main/java/com/goorm/tablepick/domain/restaurant/controller/RestaurantController.java
  src/main/java/com/goorm/tablepick/domain/restaurant/dto/request/RestaurantCategorySearchRequestDto.java
  src/main/java/com/goorm/tablepick/domain/restaurant/dto/request/RestaurantKeywordSearchRequestDto.java
  src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/MenuResponseDto.java
  src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/PagedRestaurantResponseDto.java
  src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantSearchResponseDto.java
  src/main/java/com/goorm/tablepick/domain/restaurant/exception/RestaurantErrorCode.java
  src/main/java/com/goorm/tablepick/domain/restaurant/repository/MenuRepository.java
  src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantCategoryRepository.java
  src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepository.java
  src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantService.java
  src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantServiceImpl.java
Labels: feat

#35 TP-47 로그아웃 API
  src/main/java/com/goorm/tablepick/domain/member/controller/MemberController.java
  src/main/java/com/goorm/tablepick/global/config/SecurityConfig.java
Labels: feat

#40 [TP-62] 게시물 최신순(시간순) 정렬 리팩토링
  src/main/java/com/goorm/tablepick/domain/board/service/BoardServiceImpl.java
Labels: feat

#46 Tp 78 restaurant
  src/main/java/com/goorm/tablepick/domain/board/service/BoardServiceImpl.java
  src/main/java/com/goorm/tablepick/domain/restaurant/controller/RestaurantController.java
  src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/PagedRestaurantResponseDto.java
  src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantListResponseDto.java
  src/main/java/com/goorm/tablepick/domain/restaurant/entity/Restaurant.java
  src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepository.java
  src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantService.java
  src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantServiceImpl.java
Labels: feat

#48 TP-79 cors 에러 코드 수정
  src/main/java/com/goorm/tablepick/global/config/SecurityConfig.java
  src/main/java/com/goorm/tablepick/global/config/WebConfig.java
  src/main/java/com/goorm/tablepick/global/jwt/OAuth2AuthenticationSuccessHandler.java
Labels: bug

#49 Tp 74 restaurant
  src/main/java/com/goorm/tablepick/domain/reservation/controller/ReservationController.java
  src/main/java/com/goorm/tablepick/domain/restaurant/controller/RestaurantController.java
  src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantResponseDto.java
  src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepository.java
  src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantService.java
  src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantServiceImpl.java
  src/main/java/com/goorm/tablepick/global/config/SecurityConfig.java
Labels: feat

#55 TP-81 DTO @Getter @Setter 추가
  src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardDetailResponseDto.java
  src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardListResponseDto.java
  src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardSearchResponseDto.java
  src/main/java/com/goorm/tablepick/domain/board/dto/response/MyBoardListResponseDto.java
  src/main/java/com/goorm/tablepick/domain/member/dto/MemberAddtionalInfoRequestDto.java
  src/main/java/com/goorm/tablepick/domain/member/dto/MemberResponseDto.java
  src/main/java/com/goorm/tablepick/domain/member/dto/MemberUpdateRequestDto.java
  src/main/java/com/goorm/tablepick/domain/reservation/dto/response/ReservationResponseDto.java
  src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/MenuResponseDto.java
  src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantListResponseDto.java
  src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantResponseDto.java
Labels: bug

#41 TP-59 FCM 토큰 발행 및 웹 알림 푸시
  .gitignore
  build.gradle
  src/main/java/com/goorm/tablepick/domain/member/entity/Member.java
  src/main/java/com/goorm/tablepick/domain/notification/constant/NotificationStatus.java
  src/main/java/com/goorm/tablepick/domain/notification/constant/NotificationTypes.java
  src/main/java/com/goorm/tablepick/domain/notification/controller/NotificationController.java
  src/main/java/com/goorm/tablepick/domain/notification/controller/NotificationScheduleController.java
  src/main/java/com/goorm/tablepick/domain/notification/dto/request/FCMTokenRequest.java
  src/main/java/com/goorm/tablepick/domain/notification/dto/request/NotificationRequest.java
  src/main/java/com/goorm/tablepick/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/goorm/tablepick/domain/notification/entity/Notification.java
  src/main/java/com/goorm/tablepick/domain/notification/entity/NotificationLog.java
  src/main/java/com/goorm/tablepick/domain/notification/entity/NotificationQueue.java
  src/main/java/com/goorm/tablepick/domain/notification/entity/NotificationTypes.java
  src/main/java/com/goorm/tablepick/domain/notification/repository/NotificationLogRepository.java
  src/main/java/com/goorm/tablepick/domain/notification/repository/NotificationQueueRepository.java
  src/main/java/com/goorm/tablepick/domain/notification/repository/NotificationTypesRepository.java
  src/main/java/com/goorm/tablepick/domain/notification/service/FCMService.java
  src/main/java/com/goorm/tablepick/domain/notification/service/FCMTokenService.java
  src/main/java/com/goorm/tablepick/domain/notification/service/NotificationService.java
  src/main/java/com/goorm/tablepick/domain/notification/service/ReservationNotificationScheduler.java
  src/main/java/com/goorm/tablepick/domain/reservation/entity/Reservation.java
  src/main/java/com/goorm/tablepick/domain/reservation/entity/ReservationSlot.java
  src/main/java/com/goorm/tablepick/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/goorm/tablepick/domain/reservation/service/ReservationService.java
  src/main/java/com/goorm/tablepick/global/config/FCMConfig.java
  src/main/java/com/goorm/tablepick/global/config/FilterConfig.java
  src/main/java/com/goorm/tablepick/global/config/NotificationTypesInitializer.java
  src/main/java/com/goorm/tablepick/global/config/SchedulingConfig.java
  src/main/java/com/goorm/tablepick/global/config/SecurityConfig.java
  src/main/java/com/goorm/tablepick/global/config/SwaggerConfig.java
  src/main/java/com/goorm/tablepick/global/config/TestDataInitializer.java
  src/main/java/com/goorm/tablepick/global/config/WebConfig.java
  src/main/java/com/goorm/tablepick/global/exception/GlobalExceptionHandler.java
  src/main/java/com/goorm/tablepick/global/exception/NotificationException.java
  src/main/java/com/goorm/tablepick/global/filter/ServiceWorkerHeaderFilter.java
  src/main/java/com/goorm/tablepick/global/jwt/OAuth2AuthenticationSuccessHandler.java
  src/main/resources/application.yml
  src/main/resources/static/firebase-messaging-sw.js
  src/main/resources/static/images/logo.png
  src/main/resources/static/images/warning.png
  src/main/resources/static/index.html
  src/test/java/com/goorm/tablepick/domain/global/config/NotificationTypesInitializerTest.java
  src/test/java/com/goorm/tablepick/domain/notification/controller/NotificationControllerTest.java
  src/test/java/com/goorm/tablepick/domain/notification/controller/NotificationScheduleControllerTest.java
  src/test/java/com/goorm/tablepick/domain/notification/service/FCMServiceTest.java
  src/test/java/com/goorm/tablepick/domain/notification/service/FCMTokenServiceTest.java
  src/test/java/com/goorm/tablepick/domain/notification/service/NotificationServiceTest.java
  src/test/java/com/goorm/tablepick/domain/notification/service/ReservationNotificationSchedulerTest.java
  src/test/resources/application-test.yml
  src/test/resources/firebase-service-account-test.json
Labels: feat

#64 [TP-92] 코드 디버깅
  src/main/java/com/goorm/tablepick/domain/notification/controller/NotificationController.java
  src/main/java/com/goorm/tablepick/domain/notification/dto/request/FCMTokenRequest.java
Labels: bug

#67 [TP-93] 메인페이지 게시글 4개 조회 API #65
  src/main/java/com/goorm/tablepick/domain/board/controller/BoardController.java
  src/main/java/com/goorm/tablepick/domain/board/controller/BoardTagController.java
  src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardListResponseDto.java
  src/main/java/com/goorm/tablepick/domain/board/dto/response/PagedBoardsResponseDto.java
  src/main/java/com/goorm/tablepick/domain/board/entity/Board.java
  src/main/java/com/goorm/tablepick/domain/board/exception/BoardErrorCode.java
  src/main/java/com/goorm/tablepick/domain/board/repository/BoardRepository.java
  src/main/java/com/goorm/tablepick/domain/board/service/BoardService.java
  src/main/java/com/goorm/tablepick/domain/board/service/BoardServiceImpl.java
  src/main/java/com/goorm/tablepick/domain/notification/entity/NotificationLog.java
  src/main/java/com/goorm/tablepick/global/exception/BoardException.java
Labels: feat

#68 [TP-94] 게시글 목록 페이지 6개 조회 API #66
  src/main/java/com/goorm/tablepick/domain/board/controller/BoardController.java
  src/main/java/com/goorm/tablepick/domain/board/service/BoardServiceImpl.java
Labels: feat

#81 TP-104 태그 조회 API
  src/main/java/com/goorm/tablepick/domain/notification/entity/NotificationLog.java
  src/main/java/com/goorm/tablepick/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/goorm/tablepick/domain/tag/controller/TagController.java
  src/main/java/com/goorm/tablepick/domain/tag/dto/TagResponseDto.java
  src/main/java/com/goorm/tablepick/domain/tag/repository/TagRepository.java
  src/main/java/com/goorm/tablepick/domain/tag/service/TagService.java
  src/main/java/com/goorm/tablepick/domain/tag/service/TagServiceImpl.java
  src/main/resources/application.yml
Labels: feat

#82 TP-106 카테고리 조회 API
  src/main/java/com/goorm/tablepick/domain/restaurant/controller/CategoryController.java
  src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/CategoryResponseDto.java
  src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantService.java
  src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantServiceImpl.java
Labels: feat

#90 TP-111 jwtTokenFilter 에러 해결
  src/main/java/com/goorm/tablepick/global/filter/JwtTokenFilter.java
Labels: bug

#92 [TP-114] 시큐리티 로그인 전 경로 추가
  src/main/java/com/goorm/tablepick/global/config/SecurityConfig.java
Labels: feat

#93 TP-110-board-list-api-update
  src/main/java/com/goorm/tablepick/domain/board/controller/BoardController.java
  src/main/java/com/goorm/tablepick/domain/board/dto/request/BoardRequestDto.java
  src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardListResponseDto.java
  src/main/java/com/goorm/tablepick/domain/board/service/BoardService.java
  src/main/java/com/goorm/tablepick/domain/board/service/BoardServiceImpl.java
Labels: enhancement

#98 TP-117 식당 이미지 추가
  src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantListResponseDto.java
Labels: bug

#100 TP-117 식당 이미지 추가
  src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantListResponseDto.java
Labels: feat

#101 TP-117 식당 이미지 추가
  src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantListResponseDto.java
Labels: bug

#105 [TP-120] 로그아웃 CORS 에러 해결
  src/main/java/com/goorm/tablepick/global/config/SecurityConfig.java
Labels: bug

#108 [TP-112] 게시글 상세 페이지 API 수정 #94
  src/main/java/com/goorm/tablepick/TablePickBackEndApplication.java
  src/main/java/com/goorm/tablepick/domain/board/controller/BoardController.java
  src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardDetailResponseDto.java
  src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardListResponseDto.java
  src/main/java/com/goorm/tablepick/domain/board/dto/response/PagedBoardListResponseDto.java
  src/main/java/com/goorm/tablepick/domain/board/repository/BoardRepository.java
  src/main/java/com/goorm/tablepick/domain/board/service/BoardService.java
  src/main/java/com/goorm/tablepick/domain/board/service/BoardServiceImpl.java
  src/main/java/com/goorm/tablepick/global/filter/JwtTokenFilter.java
Labels: enhancement

#111 TP-122 멤버 태그 에러 수정
  src/main/java/com/goorm/tablepick/domain/member/dto/MemberAddtionalInfoRequestDto.java
  src/main/java/com/goorm/tablepick/domain/member/entity/Member.java
  src/main/java/com/goorm/tablepick/domain/member/entity/MemberTag.java
  src/main/java/com/goorm/tablepick/domain/member/service/CustomOAuth2UserService.java
  src/main/java/com/goorm/tablepick/domain/member/service/MemberServiceImpl.java
Labels: bug

#112 TP-122 멤버 태그 에러 수정
  src/main/java/com/goorm/tablepick/domain/member/dto/MemberAddtionalInfoRequestDto.java
  src/main/java/com/goorm/tablepick/domain/member/service/MemberServiceImpl.java
Labels: bug

#107 [TP-121] FCM 민감 정보 관리 파일
  .gitignore
  src/main/resources/firebase-service-account.json
  src/main/resources/static/alarmtest.html
  src/main/resources/static/firebase-messaging-sw.js
Labels: documentation

#114 TP-123 내 예약 조회 CANCELLED 제외
  src/main/java/com/goorm/tablepick/domain/reservation/repository/ReservationRepository.java
Labels: enhancement

#116 [TP-113] 게시글 조회 API 구현 (생성은 추후 진행)
  src/main/java/com/goorm/tablepick/domain/board/controller/BoardController.java
  src/main/java/com/goorm/tablepick/domain/board/dto/request/BoardCreateResponseDto.java
  src/main/java/com/goorm/tablepick/domain/board/dto/request/BoardRequestDto.java
  src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardListResponseDto.java
  src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardSearchResponseDto.java
  src/main/java/com/goorm/tablepick/domain/board/dto/response/MyBoardListResponseDto.java
  src/main/java/com/goorm/tablepick/domain/board/entity/Board.java
  src/main/java/com/goorm/tablepick/domain/board/repository/BoardRepository.java
  src/main/java/com/goorm/tablepick/domain/board/service/BoardService.java
  src/main/java/com/goorm/tablepick/domain/board/service/BoardServiceImpl.java
  src/main/java/com/goorm/tablepick/domain/restaurant/entity/Restaurant.java
  src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepository.java
  src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantServiceImpl.java
  src/main/java/com/goorm/tablepick/global/config/SecurityConfig.java
  src/main/java/com/goorm/tablepick/global/config/WebConfig.java
Labels: refactor

#119 TP-127 리프레시 토큰 수정
  src/main/java/com/goorm/tablepick/global/jwt/OAuth2AuthenticationSuccessHandler.java
Labels: feat

#121 [TP-125] 게시글 생성 페이지 API
  src/main/java/com/goorm/tablepick/domain/board/controller/BoardController.java
  src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardCreateResponseDto.java
  src/main/java/com/goorm/tablepick/domain/board/repository/BoardImageRepository.java
  src/main/java/com/goorm/tablepick/domain/board/repository/BoardRepository.java
  src/main/java/com/goorm/tablepick/domain/board/repository/BoardTagRepository.java
  src/main/java/com/goorm/tablepick/domain/board/service/BoardService.java
  src/main/java/com/goorm/tablepick/domain/board/service/BoardServiceImpl.java
  src/main/java/com/goorm/tablepick/global/security/CustomUserDetails.java
Labels: feat

#132 TP-133 검색 API
  src/main/java/com/goorm/tablepick/domain/board/entity/BoardTag.java
  src/main/java/com/goorm/tablepick/domain/restaurant/entity/Restaurant.java
  src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepository.java
Labels: feat

#148 [TP-147] NotificationTypes 에러 디버깅 완료
  src/main/java/com/goorm/tablepick/domain/notification/entity/NotificationTypes.java
Labels: bug

#152 TP-150 멤버 createAt 추가
  src/main/java/com/goorm/tablepick/domain/member/dto/MemberResponseDto.java
  src/main/java/com/goorm/tablepick/domain/member/entity/Member.java
Labels: feat

#157 [TP-148] 알림 타이틀, 바디 수정
  src/main/java/com/goorm/tablepick/global/config/NotificationTypesInitializer.java
Labels: refactor

#160 TP-146 검색 API 태그 많은 순 정렬
  src/main/java/com/goorm/tablepick/domain/restaurant/entity/Restaurant.java
  src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepository.java
  src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantServiceImpl.java
Labels: feat

#161 [TP-155] 회원 알림 목록 조회할 때 null 나오는 것들 디버깅
  src/main/java/com/goorm/tablepick/domain/notification/repository/NotificationLogRepository.java
  src/main/java/com/goorm/tablepick/domain/notification/service/NotificationServiceImpl.java
Labels: bug

#162 TP-146 검색 API 태그 많은 순 정렬
  src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepository.java
Labels: feat

#166 [TP-155] 회원 알림 목록 안보이던 현상 디버깅
  src/main/java/com/goorm/tablepick/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/goorm/tablepick/domain/notification/service/NotificationServiceImpl.java
Labels: bug

#170 [TP-158] 사용자 정보 추가
  src/main/java/com/goorm/tablepick/domain/member/dto/MemberResponseDto.java
Labels: feat

#168 [TP-157] 알림 타이틀 수정
  src/main/java/com/goorm/tablepick/global/config/NotificationTypesInitializer.java
Labels: refactor

#171 [TP-158] 사용자 정보 추가
  src/main/java/com/goorm/tablepick/domain/member/dto/MemberResponseDto.java
Labels: feat

#175 [TP-159] 식당 검색 목록 조회 리팩토링
  src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantListResponseDto.java
  src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepository.java
Labels: feat

#178 [TP-161] 내 게시글 목록 데이터 수정
  src/main/java/com/goorm/tablepick/domain/board/dto/response/MyBoardListResponseDto.java
  src/main/java/com/goorm/tablepick/domain/board/entity/BoardTag.java
  src/main/java/com/goorm/tablepick/domain/member/service/MemberServiceImpl.java
  src/main/java/com/goorm/tablepick/global/filter/JwtTokenFilter.java
Labels: feat

#195 [TP-145] 리프레시 토큰 수정
  src/main/java/com/goorm/tablepick/domain/member/controller/MemberController.java
  src/main/java/com/goorm/tablepick/domain/member/entity/RefreshToken.java
  src/main/java/com/goorm/tablepick/global/filter/JwtTokenFilter.java
  src/main/java/com/goorm/tablepick/global/jwt/JwtProvider.java
  src/main/java/com/goorm/tablepick/global/jwt/OAuth2AuthenticationSuccessHandler.java
Labels: bug

#200 [TP-170] 로그인 에러 수정
  src/main/java/com/goorm/tablepick/domain/member/entity/RefreshToken.java
  src/main/java/com/goorm/tablepick/global/filter/JwtTokenFilter.java
Labels: bug

#204 [TP-152] 회원가입 완료 축하 알림 기능 추가
  .gitignore
  src/main/java/com/goorm/tablepick/TablePickBackEndApplication.java
  src/main/java/com/goorm/tablepick/domain/member/service/CustomOAuth2UserService.java
  src/main/java/com/goorm/tablepick/domain/member/service/MemberServiceImpl.java
  src/main/java/com/goorm/tablepick/domain/notification/controller/NotificationController.java
  src/main/java/com/goorm/tablepick/domain/notification/service/FCMServiceImpl.java
  src/main/java/com/goorm/tablepick/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/goorm/tablepick/domain/notification/service/RegisterNotificationService.java
  src/main/java/com/goorm/tablepick/domain/notification/service/RegisterNotificationServiceImpl.java
  src/main/java/com/goorm/tablepick/global/config/AsyncConfig.java
  src/main/resources/application.yml
  src/main/resources/static/alarmtest.html
Labels: feat
